spring:
  application:
    name: Angular-login-demo-project
  datasource:
    url: jdbc:mysql://mysql:3306/arvind
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aarvindkosana@gmail.com
    password: 'xwkc yorz fzmv yvfz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
